import type { OpenSourceEntry } from "@/lib/open-source/types";

/**
 * 마켓컬리 오픈소스 페이지 UI/UX 참고 목록.
 * 실제 iOS 라이브러리를 설치하지 않으며, 정보 페이지 가독성·리스트 구성 참고용.
 *
 * 항목 추가 시 docs/OPEN_SOURCE_REFERENCE.md 동일 섹션도 함께 갱신.
 */
export const UI_UX_OPEN_SOURCE_REFERENCES: OpenSourceEntry[] = [
  {
    name: "Kingfisher",
    description: "이미지 캐싱 라이브러리",
    status: "referenced",
    githubUrl: "https://github.com/onevcat/Kingfisher",
    referencePurpose: "상품·카드 이미지 lazy load, placeholder, 캐시 UX",
    appliedScreens: ["홈", "카테고리", "상품 상세", "찜", "검색"],
  },
  {
    name: "Moya",
    description: "네트워크 추상화",
    status: "referenced",
    githubUrl: "https://github.com/Moya/Moya",
    referencePurpose: "API 레이어 분리, 에러·로딩 상태 일관성",
    appliedScreens: ["로그인", "마이셀로", "장바구니", "알림"],
  },
  {
    name: "Alamofire",
    description: "HTTP 네트워킹",
    status: "referenced",
    githubUrl: "https://github.com/Alamofire/Alamofire",
    referencePurpose: "네트워크 요청 패턴, 재시도·타임아웃 UX",
    appliedScreens: ["로그인", "회원가입", "결제"],
  },
  {
    name: "Lottie",
    description: "벡터 애니메이션",
    status: "referenced",
    githubUrl: "https://github.com/airbnb/lottie-ios",
    referencePurpose: "로딩·빈 상태·온보딩 모션 톤",
    appliedScreens: ["로그인", "스플래시", "장바구니 빈 상태"],
  },
  {
    name: "Firebase",
    description: "백엔드·분석 플랫폼",
    status: "referenced",
    githubUrl: "https://github.com/firebase/firebase-ios-sdk",
    referencePurpose: "푸시·분석·원격 설정 정보 구조 참고",
    appliedScreens: ["알림", "마이셀로"],
  },
  {
    name: "RxSwift",
    description: "리액티브 프로그래밍",
    status: "referenced",
    githubUrl: "https://github.com/ReactiveX/RxSwift",
    referencePurpose: "상태 흐름·이벤트 기반 UI 업데이트",
    appliedScreens: ["검색", "카테고리 필터", "장바구니"],
  },
  {
    name: "RxGesture",
    description: "제스처 리액티브 바인딩",
    status: "referenced",
    githubUrl: "https://github.com/RxSwiftCommunity/RxGesture",
    referencePurpose: "스와이프·탭 피드백, 카드 인터랙션",
    appliedScreens: ["상품 상세", "찜", "홈 캐러셀"],
  },
  {
    name: "RxKeyboard",
    description: "키보드 표시 상태 관리",
    status: "referenced",
    githubUrl: "https://github.com/RxSwiftCommunity/RxKeyboard",
    referencePurpose: "로그인·검색 입력 시 레이아웃 대응",
    appliedScreens: ["로그인", "회원가입", "검색"],
  },
  {
    name: "ReactorKit",
    description: "단방향 상태 아키텍처",
    status: "referenced",
    githubUrl: "https://github.com/ReactorKit/ReactorKit",
    referencePurpose: "화면 상태·액션 분리, 정보 페이지 데이터 흐름",
    appliedScreens: ["마이셀로", "설정", "정책/약관"],
  },
  {
    name: "Then",
    description: "선언적 UI 구성",
    status: "referenced",
    githubUrl: "https://github.com/devxoul/Then",
    referencePurpose: "컴포넌트 초기 스타일·레이아웃 가독성",
    appliedScreens: ["정보성 페이지 전반"],
  },
  {
    name: "URLNavigator",
    description: "딥링크·라우팅",
    status: "referenced",
    githubUrl: "https://github.com/devxoul/URLNavigator",
    referencePurpose: "카테고리·검색 query 라우팅, 딥링크 구조",
    appliedScreens: ["카테고리", "검색", "상품 상세"],
  },
  {
    name: "SwiftyJSON",
    description: "JSON 파싱",
    status: "referenced",
    githubUrl: "https://github.com/SwiftyJSON/SwiftyJSON",
    referencePurpose: "API 응답 필드 표시·에러 메시지 구조",
    appliedScreens: ["마이셀로", "알림", "판매자 소개"],
  },
  {
    name: "TLPhotoPicker",
    description: "사진 선택 UI",
    status: "referenced",
    githubUrl: "https://github.com/tilltue/TLPhotoPicker",
    referencePurpose: "리뷰·프로필 이미지 선택 UX",
    appliedScreens: ["마이셀로", "상품 상세 리뷰"],
  },
  {
    name: "ReusableKit",
    description: "재사용 셀·뷰 등록",
    status: "referenced",
    githubUrl: "https://github.com/devxoul/ReusableKit",
    referencePurpose: "리스트·메뉴 행 컴포넌트 재사용",
    appliedScreens: ["마이셀로", "설정", "오픈소스", "정책/약관"],
  },
  {
    name: "KeychainAccess",
    description: "키체인 저장",
    status: "referenced",
    githubUrl: "https://github.com/kishikawakatsumi/KeychainAccess",
    referencePurpose: "토큰·자격 증명 저장 UX",
    appliedScreens: ["로그인", "마이셀로 보안"],
  },
  {
    name: "SwiftDate",
    description: "날짜·시간 처리",
    status: "referenced",
    githubUrl: "https://github.com/malcommac/SwiftDate",
    referencePurpose: "주문·알림·이벤트 날짜 표기",
    appliedScreens: ["알림", "마이셀로", "장바구니"],
  },
  {
    name: "NotificationBanner",
    description: "인앱 배너 알림",
    status: "referenced",
    githubUrl: "https://github.com/Daltron/NotificationBanner",
    referencePurpose: "토스트·배너 피드백 톤",
    appliedScreens: ["로그인", "장바구니", "찜"],
  },
  {
    name: "MarqueeLabel",
    description: "스크롤 텍스트 라벨",
    status: "referenced",
    githubUrl: "https://github.com/cbpowell/MarqueeLabel",
    referencePurpose: "긴 상품명·공지 텍스트 처리",
    appliedScreens: ["홈", "상품 상세"],
  },
  {
    name: "FloatingPanel",
    description: "바텀 시트·패널",
    status: "referenced",
    githubUrl: "https://github.com/scenee/FloatingPanel",
    referencePurpose: "필터·옵션·정렬 패널 UX",
    appliedScreens: ["검색", "카테고리", "상품 상세"],
  },
];
